name: Zebra Social
favicon: null
layout_spectrum: 0.05757308634929359
typography_spectrum: 0.13787796488031745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6886035017669201
  lightness: 0.47126849344931543
  saturation: 0.14607354905456305
  rhythmicContrast: 0.8148158411495388
purpose: []
